_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/experiment_scripts/test.py
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.17
            "5": 0.19.9
            "8":
                - 5
                - 9
            "12": 0.19.9
            "13": linux-x86_64
algo:
    value: P3O
algo_cfgs:
    value:
        adv_estimation_method: gae
        batch_size: 64
        clip: 0.2
        cost_gamma: 0.99
        cost_limit: 25
        cost_normalize: false
        critic_norm_coef: 0.001
        entropy_coef: 0
        gamma: 0.99
        kappa: 20
        kl_early_stop: true
        lam: 0.95
        lam_c: 0.95
        max_grad_norm: 40
        obs_normalize: true
        penalty_coef: 0
        reward_normalize: false
        standardized_cost_adv: true
        standardized_rew_adv: true
        steps_per_epoch: 20000
        target_kl: 0.02
        update_iters: 10
        use_cost: true
        use_critic_norm: true
        use_max_grad_norm: true
env_id:
    value: SafetyHalfCheetahVelocity-v1
exp_increment_cfgs:
    value:
        algo_cfgs:
            steps_per_epoch: 20000
        logger_cfgs:
            log_dir: ./exp-x/omnisafe_test_benchmark/SafetyHalfCheetahVelocity-v1---cab461456a593547396e0122ca8822b138afea517a2f296e615c4caea87349d7/
            use_tensorboard: false
            use_wandb: true
        seed: 4
        train_cfgs:
            device: cuda:1
            torch_threads: 8
            total_steps: 1000000
            vector_env_nums: 4
exp_name:
    value: P3O-{SafetyHalfCheetahVelocity-v1}
logger_cfgs:
    value:
        log_dir: ./exp-x/omnisafe_test_benchmark/SafetyHalfCheetahVelocity-v1---cab461456a593547396e0122ca8822b138afea517a2f296e615c4caea87349d7/
        save_model_freq: 100
        use_tensorboard: false
        use_wandb: true
        wandb_project: omnisafe
        window_lens: 100
model_cfgs:
    value:
        actor:
            activation: tanh
            hidden_sizes:
                - 64
                - 64
            lr: 0.0003
        actor_type: gaussian_learning
        critic:
            activation: tanh
            hidden_sizes:
                - 64
                - 64
            lr: 0.0003
        exploration_noise_anneal: false
        linear_lr_decay: true
        std_range:
            - 0.5
            - 0.1
        weight_initialization_mode: kaiming_uniform
seed:
    value: 4
train_cfgs:
    value:
        device: cuda:1
        epochs: 50
        parallel: 1
        torch_threads: 8
        total_steps: 1000000
        vector_env_nums: 4
